### ISSUE TITLE
Ошибка при удаление учетной записи

### ISSUE THREAD

**Issue by instant992** [mediclab/wg-admin-docker#1]
Подскажите, это у меня косяк или это баг и оно не работает? Когда создаю учетную запись для человека через админ профиль, и после этого пытаюсь ее удалить выдает окно с 500 ошибкой SERVER ERROR.
![image](https://user-images.githubusercontent.com/59600183/222928447-125c5b52-1f4b-45ab-94ec-11fd90719f7a.png)
И при попытке показать qr код ничего не происходит, на секунду на кнопке появляется загрузка и все.

**Comment by mediclab** [comment]
С QR-кодом сейчас есть непонятный баг, не подгружается JS необходимая для работы, удаление учетки проверю.

**Comment by mediclab** [comment]
Исправил. Обновитесь до версии 0.9.5 через команду `make upgrade`
